### PR TITLE
Freeze all deps

### PR DESCRIPTION
**Pull request by seanstory**
Trying to fix some recent failed builds, like:
```
+ /opt/buildkite-agent/builds/bk-agent-prod-gcp-1718609314856468176/elastic/connectors-nightly/tests/../bin/perf8 --refresh-rate 5 -t /opt/buildkite-agent/builds/bk-agent-prod-gcp-1718609314856468176/elastic/connectors-nightly/tests/../perf8-report-mysql --asyncstats --psutil --max-duration 600 --description description.txt -c /opt/buildkite-agent/builds/bk-agent-prod-gcp-1718609314856468176/elastic/connectors-nightly/tests/../bin/elastic-ingest --config-file mysql/config.yml --debug
--
  |  
  | A module that was compiled using NumPy 1.x cannot be run in
  | NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
  | versions of NumPy, modules must be compiled with NumPy 2.0.
  | Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
  |  
  | If you are a user of the module, the easiest solution will be to
  | downgrade to 'numpy<2' or try to upgrade the affected module.
  | We expect that some modules will need time to support NumPy 2.
  |  
  | Traceback (most recent call last):  File "/opt/buildkite-agent/builds/bk-agent-prod-gcp-1718609314856468176/elastic/connectors-nightly/tests/../bin/perf8", line 5, in <module>
  | from perf8.cli import main
  | File "/opt/buildkite-agent/builds/bk-agent-prod-gcp-1718609314856468176/elastic/connectors-nightly/lib/python3.10/site-packages/perf8/__init__.py", line 23, in <module>
  | from perf8.plugins.base import enable, disable, measure  # NOQA
  | File "/opt/buildkite-agent/builds/bk-agent-prod-gcp-1718609314856468176/elastic/connectors-nightly/lib/python3.10/site-packages/perf8/plugins/__init__.py", line 20, in <module>
  | from perf8.plugins import _psutil, _cprofile, _memray, _pyspy, _asyncstats  # NOQA
  | File "/opt/buildkite-agent/builds/bk-agent-prod-gcp-1718609314856468176/elastic/connectors-nightly/lib/python3.10/site-packages/perf8/plugins/_psutil.py", line 25, in <module>
  | import matplotlib.ticker as tkr
  | File "/opt/buildkite-agent/builds/bk-agent-prod-gcp-1718609314856468176/elastic/connectors-nightly/lib/python3.10/site-packages/matplotlib/__init__.py", line 129, in <module>
  | from . import _api, _version, cbook, _docstring, rcsetup
  | File "/opt/buildkite-agent/builds/bk-agent-prod-gcp-1718609314856468176/elastic/connectors-nightly/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 27, in <module>
  | from matplotlib.colors import Colormap, is_color_like
  | File "/opt/buildkite-agent/builds/bk-agent-prod-gcp-1718609314856468176/elastic/connectors-nightly/lib/python3.10/site-packages/matplotlib/colors.py", line 56, in <module>
  | from matplotlib import _api, _cm, cbook, scale
  | File "/opt/buildkite-agent/builds/bk-agent-prod-gcp-1718609314856468176/elastic/connectors-nightly/lib/python3.10/site-packages/matplotlib/scale.py", line 22, in <module>
  | from matplotlib.ticker import (
  | File "/opt/buildkite-agent/builds/bk-agent-prod-gcp-1718609314856468176/elastic/connectors-nightly/lib/python3.10/site-packages/matplotlib/ticker.py", line 138, in <module>
  | from matplotlib import transforms as mtransforms
  | File "/opt/buildkite-agent/builds/bk-agent-prod-gcp-1718609314856468176/elastic/connectors-nightly/lib/python3.10/site-packages/matplotlib/transforms.py", line 49, in <module>
  | from matplotlib._path import (
  | AttributeError: _ARRAY_API not found
```

I was able to reproduce this by running `make clean` and then installing from the `requirements.txt` and running a 
```
bin/perf8 --all -c test.py
```

where test.py was just `print("hello, world")`.

Steps to resolve:

1. `make clean`
2. edit `requirements.txt` to have `numpy<2.0.0`
3. `make install` (I added this, but just install from requirements.txt into a venv)
4. `pip freeze > requirements.txt`

This freezes all our deps and their transitives at precise versions. Previously, we weren't pinning transitives.

### CODE REVIEW

**Comment by artem-shelkovnikov** [comment]
I've checked a bit and the problem is with `matplotlib` - they declared their dependency on `numpy` with `>1.X` and then `2.X` version was dropped with incompatible changes. Upgrading `mathplotlib` seems to fix everything too, maybe we can just do it?

**Comment by seanstory** [comment]
> Upgrading mathplotlib seems to fix everything too, maybe we can just do it?

Sure. By "fix everything" does it make perf8 CI pass?

I do still think that we should `pip freeze > requirements.txt` to prevent issues like this from happening in the future. And maybe we should create a tag in perf8 to reference, instead of main?

**Comment by artem-shelkovnikov** [comment]
> Sure. By "fix everything" does it make perf8 CI pass?

I think CI is just broken here.

> I do still think that we should pip freeze > requirements.txt to prevent issues like this from happening in the future. And maybe we should create a tag in perf8 to reference, instead of main?

I'm not sure about it cause it has potential to break stuff weirdly in connectors repo - there we don't have hard dependencies for a lot of packages, for example for all dependencies of dependencies. If there's gonna be a conflict/security issue in connectors repo, it will require an update here.

So I'd just fix the outlier here - `matplotlib` - and just forget about this repo until next time.

**Comment by seanstory** [comment]
closing in favor of https://github.com/elastic/perf8/pull/17

**Pull request closed without merging**
